// <auto-generated />
namespace BAC007.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BAC007Initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BAC007Initial));
        
        string IMigrationMetadata.Id
        {
            get { return "202111240759197_BAC007-Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
